# Production Configuration for Persistent Cognitive Multi-Agent System
# Generated automatically during deployment

system_name: "Persistent Cognitive Multi-Agent System"
version: "2.0.0"
environment: "production"
debug_mode: false

database:
  cognitive_db_path: "/opt/cognitive/data/cognitive_system.db"
  server_db_path: "/opt/cognitive/data/server_system.db"
  backup_enabled: true
  backup_interval_hours: 24
  backup_retention_days: 90
  auto_vacuum: true
  wal_mode: true
  sync_mode: "NORMAL"

server:
  enabled: true
  host: "0.0.0.0"
  port: 8080
  ssl_enabled: false
  max_connections: 1000
  session_timeout_hours: 24
  memory_backup_interval_hours: 1
  distributed_mode: false

cognitive:
  memory_consolidation_enabled: true
  memory_consolidation_interval_hours: 6
  memory_decay_enabled: true
  memory_decay_rate: 0.1
  working_memory_capacity: 20
  reasoning_chain_timeout_minutes: 60
  strategic_planning_enabled: true
  meta_cognitive_enabled: true
  background_processing_enabled: true
  inter_agent_coordination: true

logging:
  level: "INFO"
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
  file_enabled: true
  file_path: "/opt/cognitive/logs/system.log"
  file_max_size_mb: 100
  file_backup_count: 5
  console_enabled: true
  structured_logging: true

security:
  authentication_enabled: false
  api_key_required: false
  rate_limiting_enabled: true
  rate_limit_per_minute: 100
  encryption_enabled: false
  audit_logging: true
  secure_memory_erasure: true
  safety_agent_required: true

performance:
  max_worker_threads: 8
  memory_cache_size_mb: 512
  query_timeout_seconds: 30
  batch_processing_enabled: true
  batch_size: 100
  connection_pool_size: 20
  async_processing: true
  optimization_level: "balanced"
