# Governance Configuration for Cyber-LLM
# Enterprise governance, compliance, and AI ethics settings

# Compliance Frameworks to Support
compliance_frameworks:
  - GDPR
  - SOC2
  - NIST
  - ISO27001
  - PCI_DSS

# Governance Policies
governance_policies:
  data_retention_days: 90
  model_approval_required: true
  bias_threshold: 0.1
  safety_threshold: 0.9
  audit_log_retention: 365
  automated_compliance_checking: true

# AI Ethics Configuration
ai_ethics:
  ethics_frameworks:
    - EU_AI_ACT
    - NIST_AI_RMF
    - RESPONSIBLE_AI_MICROSOFT
  
  bias_thresholds:
    demographic_parity: 0.1
    equalized_odds: 0.1
    equal_opportunity: 0.1
    calibration: 0.05
  
  fairness_requirements:
    minimum_fairness_score: 0.8
    demographic_groups:
      - gender
      - age
      - ethnicity
      - location
      - experience_level
    protected_attributes:
      - race
      - gender
      - religion
      - political_affiliation
      - sexual_orientation
  
  transparency_requirements:
    minimum_explainability_score: 0.7
    explanation_methods:
      - SHAP
      - LIME
      - attention_weights
      - gradient_attribution
    local_explanations_required: true
    global_explanations_required: true

# Monitoring and Alerting
monitoring:
  continuous_bias_monitoring: true
  fairness_drift_detection: true
  explanation_quality_tracking: true
  compliance_violation_alerting: true
  automated_reporting: true
  
  alert_thresholds:
    bias_drift: 0.05
    fairness_degradation: 0.1
    compliance_violation: 0.0
    safety_threshold_breach: 0.01

# Notification Settings
notifications:
  critical_violations: true
  compliance_reports: true
  model_lifecycle_events: true
  bias_assessment_results: true
  ethics_violations: true
  
  notification_channels:
    - email
    - slack
    - dashboard
    - api_webhook

# Automated Remediation
automated_remediation:
  enabled: true
  auto_quarantine_models: true
  auto_generate_reports: true
  auto_apply_bias_mitigation: false  # Require human approval
  auto_update_compliance_status: true

# Risk Assessment
risk_assessment:
  risk_matrix:
    low: 
      score_range: [0.8, 1.0]
      actions: ["monitor", "log"]
    medium:
      score_range: [0.6, 0.8]
      actions: ["notify", "investigate", "monitor"]
    high:
      score_range: [0.3, 0.6]
      actions: ["escalate", "investigate", "remediate"]
    critical:
      score_range: [0.0, 0.3]
      actions: ["quarantine", "escalate", "immediate_remediation"]

# Audit and Compliance
audit:
  comprehensive_audit_trail: true
  regulatory_reporting: true
  compliance_dashboard: true
  periodic_assessments: true
  
  audit_frequency:
    bias_assessment: "monthly"
    compliance_review: "quarterly"
    governance_audit: "annually"
    ethics_review: "quarterly"

# Data Governance
data_governance:
  data_lineage_required: true
  consent_tracking: true
  data_minimization: true
  right_to_explanation: true
  data_deletion_capability: true
  
  data_classification:
    - public
    - internal
    - confidential
    - restricted
    - personal_data

# Model Lifecycle Governance
model_lifecycle:
  approval_gates:
    development_to_testing: ["bias_assessment", "safety_check"]
    testing_to_staging: ["compliance_review", "ethics_approval"]
    staging_to_production: ["governance_approval", "final_assessment"]
  
  required_documentation:
    - model_card
    - data_lineage
    - bias_assessment_report
    - explainability_report
    - compliance_checklist
    - ethics_review

# Integration Settings
integrations:
  mlflow_tracking: true
  kubernetes_rbac: true
  prometheus_monitoring: true
  grafana_dashboards: true
  external_audit_systems: true
